<?php

$buttons[]=array('klawisz'=>'Alt1','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liRejestryVAT').addClass('active');
	parent.$('#RejestryVAT').addClass('active');
	parent.$('#iframeRejestryVAT').focus();
");
$buttons[]=array('klawisz'=>'Alt2','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liTowary').addClass('active');
	parent.$('#Towary').addClass('active');
	parent.$('#iframeTowary').focus();
");
$buttons[]=array('klawisz'=>'Alt3','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liDekrety').addClass('active');
	parent.$('#Dekrety').addClass('active');
	parent.$('#iframeDekrety').focus();
");
$buttons[]=array('klawisz'=>'Alt4','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liKPiR').addClass('active');
	parent.$('#KPiR').addClass('active');
	parent.$('#iframeKPiR').focus();
");
$buttons[]=array('klawisz'=>'Alt5','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liEwidSprz').addClass('active');
	parent.$('#EwidSprz').addClass('active');
	parent.$('#iframeEwidSprz').focus();
");
$buttons[]=array('klawisz'=>'Alt6','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liEwidPrzeb').addClass('active');
	parent.$('#EwidPrzeb').addClass('active');
	parent.$('#iframeEwidPrzeb').focus();
");
$buttons[]=array('klawisz'=>'Alt7','nazwa'=>'','js'=>"
	parent.$('li').removeClass('active');
	parent.$('div.tab-pane:not(#home)').removeClass('active');
	parent.$('#liEwidWypo').addClass('active');
	parent.$('#EwidWypo').addClass('active');
	parent.$('#iframeEwidWypo').focus();
");
