Esc|Esc - wyjžcie|won:=.t.|
S|Szukaj|Szukaj(nr)|
X|X=Sortuj|CreateIndex(kolumny[nr])|
T|Total|ShowDBES()|
W|Wydruk|Drukuj('analiz66')|
A|Aktualizacja=ENTER|DokAna6('ANALIZA6,Podaj parametry procedury,,,,,,,3','FV,RU,FVK,RUK','Zestawienie sprzeda§y')|
ENTER||DokAna6('ANALIZA6,Podaj parametry procedury,,,,,,,3','FV,RU,FVK,RUK','Zestawienie sprzeda§y')|
Q||DokAna6('ANALIZA6,Podaj parametry procedury,,,,,,,3','FV,RU,FVK,RUK','Zestawienie sprzeda§y',1)|
