Esc|Esc - wyjžcie|won:=.t.|
S|Szukaj|Szukaj(nr)|
X|X=Sortuj|CreateIndex(kolumny[nr])|
T|Total|ShowDBES()|
W|Wydruk|Drukuj()|
A|Aktualizacja=ENTER|DokAna6('ANALIZA6,Podaj parametry procedury,,,,,,,3','FV,RU,FVK,RUK','Sprzeda§ (dokumenty)')|
ENTER||DokAna6('ANALIZA6,Podaj parametry procedury,,,,,,,3','FV,RU,FVK,RUK','Sprzeda§ (dokumenty)')|
Q||DokAna6('ANALIZA6,Podaj parametry procedury,,,,,,,3','FV,RU,FVK,RUK','Sprzeda§ (dokumenty)',1)|
