Esc|Esc - wyjžcie|won:=.t.|
S|Szukaj|nr|
T|Total|ShowDBES()|
X|X=Sortuj|CreateIndex(kolumny[nr])|
W|Wydruk|Drukuj()|
A|Aktualizacja=ENTER|Zwolnij(baza),ON(baza),DokAna11('ANALIZA1,Podaj parametry procedury,,,,,,,2','FV,RU,FVK,RUK','Sprzeda§ przez kontrahent¢w tytu’u'),Jest_baza('ANALIZA1'),CreateIndex(kolumny[1]),DBGoTop()|
ENTER||Zwolnij(baza),ON(baza),DokAna11('ANALIZA1,Podaj parametry procedury,,,,,,,2','FV,RU,FVK,RUK','Sprzeda§ przez kontrahent¢w tytu’u'),Jest_baza('ANALIZA1'),CreateIndex(kolumny[1]),DBGoTop()|
