Esc|Esc-wyjžcie|SumSub('ROB','5','12')|
S|Szukaj|SysMySeek('',nr)|
T|Total|TotDBES()|
W|Wydruk|Drukuj('dokzal')|
F|Formularz|NewSysForm('DOKZA,Dane bie§†cej pozycji')|
U|Usu¤|Kasuj()|
D|Dopisz=Enter|NewSysDopisz('DOKZA,Nowa pozycja,,,,,,,3',,,"ROB2->ID_F:=FIRMY->ID_F,ROB2->ID_D:=ROB->ID,ROB2->ID:=ROB2->(GetLast(2,2)+1),ROB2->DATAW:=Date()")|
Enter||NewSysDopisz('DOKZA,Nowa pozycja,,,,,,,3',,,"ROB2->ID_F:=FIRMY->ID_F,ROB2->ID_D:=ROB->ID,ROB2->ID:=ROB2->(GetLast(2,2)+1),ROB2->DATAW:=Date()")|
