Modyfikacja danych
F1 - pomoc
1|2|3|4|5|6|7|8|9|10|11|
Nazwa formularza :|LP pola :|nazwa pola :|zmienna pola :|picture :|wiersz/kolumna :|,|funkcja valid :| |funkcja help :| |
@K XXXXXXXXXX|99|@K XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|@K XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|@K XXXXXXXXXXXXXXXXXXX|99|99|999|@KS50|999|@KS50|
1|2|3|4|5|6|7|8|9|10|11|
1|2|3|4|5|6|7|8|9|10|11|
8|1|20|78|1|
1|2|
2|11|
3|8|
4|6|
5|1|
6|6|
6|25|
8|1|
8|20|
9|2|
9|20|