rem c:
rem cd\Place
rem pl.bat
rem pause

@echo off

c:
cd\arrakis
rem keybpl.exe MA ON
egapl.exe MA ACTIVE
rem pause
pol_klaw
pol_znak vga

rem subst g: c:\DYSK_G
rem g:

rem set include=
set PATH=C:\WINDOWS\COMMAND;c:\ARRAKIS
set arek=
set arek=OK
set stacja=
set MONITOR=
set MONITOR=HIGH
REM set HANDEL=1
set HANDEL=
rem set ARRAKIS=A
rem set ARRAKIS=2

rem cd\mistral
rem cd\stem2003.10

rem c:\arrakis\r.exe C:\Archiwum\Mistral\Arrakis\2009 C:\Archiwum\Mistral\Arrakis\wzory C:\Archiwum\Mistral\Arrakis\system

cd\arrakis\fk\clch.fk
c:\arrakis\r.exe . c:\arrakis\fk\clch.fk\wzory c:\arrakis\fk\clch.fk\system 

rem cd\arrakis\fk\p13
rem c:\arrakis\r.exe . \arrakis\fk\P13\wzory \arrakis\fk\P13\system

rem cd\arrakis\fk\clch.pl
rem cd\arrakis\fk\placeibp
rem cd\arrakis\Mariol
rem cd\arrakis\fk\sojta
rem cd \Archiwum\Mistral\Arrakis\
rem cd \Archiwum\Mistral\FK.99\
rem RETSAT.BAT

rem c:\arrakis\r.exe . \arrakis\Mariol\wzory \arrakis\Mariol\system
rem c:\arrakis\r.exe MAG_2007 C:\Arrakis\FK\CLCH.mag\wzory C:\Arrakis\FK\CLCH.mag\system
rem c:\arrakis\r.exe C:\Arrakis\FK\elast.07\2007 C:\Arrakis\FK\elast.07\wzory C:\Arrakis\FK\elast.07\system
rem c:\arrakis\r.exe C:\Archiwum\Mistral\FK.99\2009 C:\Archiwum\Mistral\FK.99\wzory C:\Archiwum\Mistral\FK.99\system
rem C:\Arrakis\FK\mistral\system
rem c:\arrakis\r.exe C:\Arrakis\FK\Filutek.pl C:\Arrakis\FK\Filutek.pl\wzory c:\Arrakis\FK\Filutek.pl\system
rem c:\arrakis\r.exe C:\Arrakis\Zelow.04 C:\Arrakis\wzory C:\Arrakis\system
rem c:\arrakis\r.exe . c:\arrakis\fk\clch.pl\wzory c:\arrakis\fk\clch.pl\system 

c:
cd\arrakis
keybpl.exe MA RE
egapl.exe MA REMOVE

cd\arek.m\firmy\ewidens
