rem c:
rem cd\Place
rem pl.bat
rem pause

@echo off

c:
cd\arrakis

rem pol_klaw
rem pol_znak vga

keybpl.exe LA ON
rem egapl.exe MA ACTIVE

rem subst g: c:\DYSK_G
rem g:

rem set include=
set PATH=C:\WINDOWS\COMMAND;c:\ARRAKIS
set arek=
set arek=OK
set stacja=
set MONITOR=
rem set MONITOR=HIGH
REM set HANDEL=1
set HANDEL=
rem set ARRAKIS=A
rem set ARRAKIS=2

rem cd\arrakis\fk\AM2013
rem c:\arrakis\r.exe

rem cd\arrakis\FK\Inez2016
rem c:\arrakis\r.exe . c:\arrakis\fk\Inez2016\wzory c:\arrakis\fk\Inez2016\system 

rem cd\mistral
rem cd\stem2003.10

rem cd \Archiwum\Mistral\Arrakis\2009
rem C:\Arrakis\R.EXE C:\Archiwum\Mistral\ARRAKIS\2009 C:\Archiwum\Mistral\ARRAKIS\WZORY C:\Archiwum\Mistral\ARRAKIS\SYSTEM
pause

call c:\Archiwum\P13\subst_ON.BAT
call c:\Archiwum\P13\Arrakis.BAT
rem call c:\Archiwum\P13\ArrakisK.BAT
rem call c:\Archiwum\P13\P13nowy.BAT

rem pause

rem cd\arrakis\fk\XXX2011
rem c:\arrakis\r.exe

rem cd\arrakis\FK\Izofol
rem c:\arrakis\r.exe . c:\arrakis\fk\Izofol\wzory c:\arrakis\fk\Izofol\system 

rem cd\arrakis\fk\Tera2014
rem Tera2014.bat

rem cd\arrakis\fk\clch.fk
rem c:\arrakis\r.exe . c:\arrakis\fk\clch.fk\wzory c:\arrakis\fk\clch.fk\system 

rem cd\arrakis\fk\place
rem c:\arrakis\r.exe . c:\arrakis\fk\place\wzory c:\arrakis\fk\place\system 

rem cd\arrakis\fk\placeibp
rem c:\arrakis\r.exe . c:\arrakis\fk\placeibp\wzory c:\arrakis\fk\placeibp\system 

rem cd\arrakis\fk\p13
rem c:\arrakis\r.exe . \arrakis\fk\P13\wzory \arrakis\fk\P13\system

rem cd\arrakis\fk\clch.pl
rem c:\arrakis\r.exe . c:\arrakis\fk\clch.pl\wzory c:\arrakis\fk\clch.pl\system 

rem cd\arrakis\fk\placeibp

rem cd\arrakis\Mariol

rem cd\arrakis\KraBatSe.11
rem c:\arrakis\r.exe . \arrakis\KraBatSe.11\wzory \arrakis\KraBatSe.11\system

rem cd\arrakis\fk\sojta
rem cd \Archiwum\Mistral\Arrakis\
rem cd \Archiwum\Mistral\FK.99\
rem RETSAT.BAT

rem c:\arrakis\r.exe . \arrakis\Mariol\wzory \arrakis\Mariol\system
rem c:\arrakis\r.exe MAG_2007 C:\Arrakis\FK\CLCH.mag\wzory C:\Arrakis\FK\CLCH.mag\system
rem c:\arrakis\r.exe C:\Arrakis\FK\elast.07\2007 C:\Arrakis\FK\elast.07\wzory C:\Arrakis\FK\elast.07\system
rem c:\arrakis\r.exe C:\Archiwum\Mistral\FK.99\2009 C:\Archiwum\Mistral\FK.99\wzory C:\Archiwum\Mistral\FK.99\system
rem C:\Arrakis\FK\mistral\system
rem c:\arrakis\r.exe C:\Arrakis\FK\Filutek.pl C:\Arrakis\FK\Filutek.pl\wzory c:\Arrakis\FK\Filutek.pl\system
rem c:\arrakis\r.exe C:\Arrakis\Zelow.04 C:\Arrakis\wzory C:\Arrakis\system
rem c:\arrakis\r.exe . c:\arrakis\fk\clch.pl\wzory c:\arrakis\fk\clch.pl\system 

c:
cd\arrakis
keybpl.exe MA RE
egapl.exe MA REMOVE

cd\arek.m\firmy\ewidens
